PROG =	fix16c

SRCS =	 read4kb.f  write4kb.f fix16c.f

OBJDIR= ./obj
SRCDIR= ./src

SRCS := $(foreach src,$(SRCS),$(SRCDIR)/$(src))
OBJS := $(SRCS:$(SRCDIR)/%.f=$(OBJDIR)/%.o)

LIBS =	

FC = gfortran
FFLAGS = -O2 -fbounds-check -fno-range-check -ffree-line-length-none
LDFLAGS = -s

all: $(PROG)

$(OBJS): $(OBJDIR)/%.o : $(SRCDIR)/%.f
	$(FC) $(FFLAGS) -c $< -o $@
	
$(PROG): $(OBJS)
	$(FC) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)

clean:
	rm -f $(PROG) $(OBJS) *.mod

.SUFFIXES: $(SUFFIXES) .f90


