PROG =	fix16c

SRCS =	 read4kb.f  write4kb.f fix16c.f

OBJS =	fix16c.o  read4kb.o  write4kb.o 


LIBS =	

CC = cc
CFLAGS = -O
FC = g77
FFLAGS = -O -Wall
F90 = f90
F90FLAGS = -O
LDFLAGS = -s

all: $(PROG)

$(PROG): $(OBJS)
	$(FC) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)

clean:
	rm -f $(PROG) $(OBJS) *.mod

.SUFFIXES: $(SUFFIXES) .f90

.f90.o:
	$(F90) $(F90FLAGS) -c $<

